<?php

/**
 * @file
 * D8: Bootstrap Tour module.
 */

/**
 * Implements hook_page_attachments().
 */
function bs_tour_page_attachments(array &$page) {
  $config_factory = \Drupal::configFactory();
  $config = $config_factory->get('bs_tour.settings');

  $tour = array(
    'keyboard' => (bool)$config->get('keyboard'),
    'debug' => (bool)$config->get('debug'),
    'autoplay' => (bool)$config->get('autoplay'),
    'number_of_tips' => $config->get('number_of_tips'),
    'steps' => $config->get('steps'),
  );

  // Attach libraries
  $page['#attached']['library'][] = 'bs_tour/bootstrap.tour';

  // Export settings
  $page['#attached']['drupalSettings']['bs_tour']['tour'] = $tour;
}

/**
 * Implements hook_theme().
 */
function bs_tour_theme($existing, $type, $theme, $path) {
  return array('bs_tour_block' =>
    array(
      'variables' => array(
        'block_settings' => NULL,
      ),
      'template' => 'block--bs-tour--block'
    )
  );
}
