<?php

/**
 * @file
 * D8: Bootstrap Tour module.
 */

/**
 * Implements hook_page_attachments().
 */
function bs_tour_page_attachments(array &$page) {
  $config_factory = \Drupal::configFactory();
  $config = $config_factory->get('bs.tour.settings');

  $keyboard = $config->get('keyboard');
  $debug = $config->get('debug');
  $number_of_tips = $config->get('number_of_tips');
  $steps = $config->get('steps');

  $tour = array(
    'keyboard' => $config->get('keyboard'),
    'debug' => $config->get('debug'),
    'number_of_tips' => $config->get('number_of_tips'),
    'steps' => $config->get('steps'),
  );

  // Export settings
  $page['#attached']['drupalSettings']['bs_tour']['tour'] = $tour;

  // Attach libraries
  $page['#attached']['library'][] = 'bs_tour/bootstrap.tour';
}
